id: jellyfin
name: Jellyfin
description: Free and open-source media server for streaming movies, TV shows, and music.
version: "1.0.0"
category: media
tags:
  - streaming
  - media-server
  - entertainment
  - self-hosted

icon: https://jellyfin.org/images/logo.svg
repository: https://github.com/jellyfin/jellyfin
documentation: https://jellyfin.org/docs/

docker:
  image: jellyfin/jellyfin:10.9.11
  ports:
    - container: 8096
      host: 8096
      protocol: tcp
      description: Web UI
    - container: 8920
      host: 8920
      protocol: tcp
      description: HTTPS Web UI (optional)
  volumes:
    - container: /config
      host: ./config
      mode: rw
      description: Configuration files
    - container: /cache
      host: ./cache
      mode: rw
      description: Transcoding cache
    - container: /media
      host: /path/to/media
      mode: ro
      description: Media library (customize path)
  environment:
    - name: TZ
      value: UTC
      required: false
      description: Timezone
    - name: JELLYFIN_PublishedServerUrl
      value: ""
      required: false
      description: Public URL for the server

requirements:
  memory: "2GB"
  cpu: "2"
  storage: "10GB"

featured: true
