id: nextcloud
name: Nextcloud
description: Self-hosted productivity platform for file sync, sharing, and collaboration.
version: "1.0.0"
category: storage
tags:
  - file-sync
  - collaboration
  - cloud-storage
  - productivity

icon: https://nextcloud.com/wp-content/uploads/2022/11/nextcloud-logo-blue-transparent.svg
repository: https://github.com/nextcloud/server
documentation: https://docs.nextcloud.com/server/latest/admin_manual/

docker:
  image: nextcloud:30.0.4
  ports:
    - container: 80
      host: 8082
      protocol: tcp
      description: Web UI
  volumes:
    - container: /var/www/html
      host: ./html
      mode: rw
      description: Application files
    - container: /var/www/html/data
      host: ./data
      mode: rw
      description: User data storage
  environment:
    - name: TZ
      value: UTC
      required: false
      description: Timezone
    - name: MYSQL_HOST
      value: ""
      required: false
      description: MySQL database host
    - name: MYSQL_DATABASE
      value: ""
      required: false
      description: MySQL database name
    - name: MYSQL_USER
      value: ""
      required: false
      description: MySQL username
    - name: MYSQL_PASSWORD
      value: ""
      required: false
      description: MySQL password

requirements:
  memory: "512MB"
  cpu: "1"
  storage: "10GB"

featured: true

healthcheck:
  endpoint: /status.php
  port: 8082
  protocol: http
