id: heimdall
name: Heimdall
description: Application dashboard and launcher for organizing your self-hosted services.
version: "1.0.0"
category: utility
tags:
  - dashboard
  - launcher
  - homepage
  - organizer

icon: https://heimdall.site/img/heimdall-icon-small.png
repository: https://github.com/linuxserver/Heimdall
documentation: https://heimdall.site/

docker:
  image: lscr.io/linuxserver/heimdall:v2.6.3-ls283
  ports:
    - container: 80
      host: 8083
      protocol: tcp
      description: Web UI (HTTP)
    - container: 443
      host: 8443
      protocol: tcp
      description: Web UI (HTTPS)
  volumes:
    - container: /config
      host: ./config
      mode: rw
      description: Configuration and data
  environment:
    - name: TZ
      value: UTC
      required: false
      description: Timezone
    - name: PUID
      value: "1000"
      required: false
      description: User ID for file permissions
    - name: PGID
      value: "1000"
      required: false
      description: Group ID for file permissions

requirements:
  memory: "128MB"
  cpu: "0.5"
  storage: "500MB"

featured: false

healthcheck:
  endpoint: /
  port: 8083
  protocol: http
