name: Feature Request
description: Suggest an improvement to the marketplace
labels: ["enhancement"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area does this affect?
      options:
        - App definitions
        - Validation
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this be useful?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?
