name: New App Request
description: Request a new app to be added
labels: ["new-app"]
body:
  - type: input
    id: name
    attributes:
      label: App Name
      placeholder: e.g., Plex, Sonarr, Home Assistant
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - automation
        - media
        - monitoring
        - networking
        - security
        - storage
        - utility
    validations:
      required: true

  - type: input
    id: repository
    attributes:
      label: Repository URL
      placeholder: https://github.com/...
    validations:
      required: true

  - type: input
    id: docker-image
    attributes:
      label: Docker Image
      placeholder: e.g., plexinc/pms-docker:1.32.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the app (20-200 chars)
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why Add This App?
      description: Why would this be useful for tomo users?
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: App is open source or has a free tier
        - label: Docker image is from a trusted registry
        - label: I'm willing to help maintain this app definition
