id: netdata
name: Netdata
description: Real-time performance and health monitoring for systems and applications.
version: "1.0.0"
category: monitoring
tags:
  - real-time
  - performance
  - system-metrics
  - health

icon: https://www.netdata.cloud/favicon-32x32.png
repository: https://github.com/netdata/netdata
documentation: https://learn.netdata.cloud/docs/

docker:
  image: netdata/netdata:v2.1.0
  ports:
    - container: 19999
      host: 19999
      protocol: tcp
      description: Web UI
  volumes:
    - container: /etc/netdata
      host: ./config
      mode: rw
      description: Configuration files
    - container: /var/lib/netdata
      host: ./data
      mode: rw
      description: Metrics database
  environment:
    - name: TZ
      value: UTC
      required: false
      description: Timezone

requirements:
  memory: "256MB"
  cpu: "0.5"
  storage: "2GB"

featured: false

healthcheck:
  endpoint: /api/v1/info
  port: 19999
  protocol: http
