id: portainer
name: Portainer CE
description: Lightweight container management UI for Docker and Kubernetes.
version: "1.0.0"
category: utility
tags:
  - docker
  - containers
  - management
  - kubernetes

icon: https://www.portainer.io/hubfs/portainer-logo-black.svg
repository: https://github.com/portainer/portainer
documentation: https://docs.portainer.io/

docker:
  image: portainer/portainer-ce:2.21.4
  ports:
    - container: 9443
      host: 9443
      protocol: tcp
      description: Web UI (HTTPS)
    - container: 8000
      host: 8000
      protocol: tcp
      description: Edge agent communication
  volumes:
    - container: /data
      host: ./data
      mode: rw
      description: Portainer data and settings
    - container: /var/run/docker.sock
      host: /var/run/docker.sock
      mode: ro
      description: Docker socket (required)
  environment:
    - name: TZ
      value: UTC
      required: false
      description: Timezone

requirements:
  memory: "512MB"
  cpu: "1"
  storage: "1GB"

featured: true
