id: authelia
name: Authelia
description: Authentication and authorization server providing two-factor and SSO for applications.
version: "1.0.0"
category: security
tags:
  - authentication
  - sso
  - two-factor
  - identity

icon: https://www.authelia.com/images/branding/logo-cropped.png
repository: https://github.com/authelia/authelia
documentation: https://www.authelia.com/docs/

docker:
  image: authelia/authelia:4.38.19
  ports:
    - container: 9091
      host: 9091
      protocol: tcp
      description: Web UI and API
  volumes:
    - container: /config
      host: ./config
      mode: rw
      description: Configuration and secrets
  environment:
    - name: TZ
      value: UTC
      required: false
      description: Timezone
    - name: AUTHELIA_JWT_SECRET
      value: ""
      required: true
      description: JWT signing secret
    - name: AUTHELIA_SESSION_SECRET
      value: ""
      required: true
      description: Session encryption secret
    - name: AUTHELIA_STORAGE_ENCRYPTION_KEY
      value: ""
      required: true
      description: Storage encryption key

requirements:
  memory: "128MB"
  cpu: "0.5"
  storage: "100MB"

featured: true

healthcheck:
  endpoint: /api/health
  port: 9091
  protocol: http
