id: uptime-kuma
name: Uptime Kuma
description: Self-hosted monitoring tool for tracking website and service uptime status.
version: "1.0.0"
category: monitoring
tags:
  - uptime
  - status-page
  - notifications
  - health-check

icon: https://uptime.kuma.pet/img/icon.svg
repository: https://github.com/louislam/uptime-kuma
documentation: https://github.com/louislam/uptime-kuma/wiki

docker:
  image: louislam/uptime-kuma:1.23.16
  ports:
    - container: 3001
      host: 3001
      protocol: tcp
      description: Web UI
  volumes:
    - container: /app/data
      host: ./data
      mode: rw
      description: Application data and SQLite database
  environment:
    - name: TZ
      value: UTC
      required: false
      description: Timezone

requirements:
  memory: "256MB"
  cpu: "0.5"
  storage: "1GB"

featured: false

healthcheck:
  endpoint: /
  port: 3001
  protocol: http
